'use strict';

// Reconciler: after a deploy, keep the user's EXACT pre-deploy diagram and only
// mark the resources that were NOT deployed (in red, "not deployed"). If every
// resource came up, the diagram is left byte-for-byte unchanged.
//
// Design: deterministic everywhere except deciding WHICH nodes failed. The
// diagram is never regenerated by the LLM — we strip any prior failure marks to
// recover the clean design, then append D2 style overrides + a label suffix to
// the failed node(s) (preserving the original layout/styling exactly). The LLM
// call only classifies which node IDs were not deployed, given the full
// (cumulative) deploy log, so it can reason about dependency cascades (e.g. an
// RDS that never got created because its VPC failed). A deterministic containment
// cascade then guarantees every resource inside a failed container is marked too.
//
// Classification reads the cumulative `workflow` (not the per-run queue) so that
// a "Retry deploy" from partial mode sees the full history: a bucket created on
// attempt 1 that errors "already exists" on attempt 2 still counts as deployed.

import { getGemini, MODELS } from '../shared/client.js';
import { loadPrompt, fill } from '../shared/prompt.js';
import { stripCodeFences } from '../../diagram.js';
import { stripAnnotations, buildNodeModel, annotateFailedNodes } from '../shared/diagramMarks.js';
import * as store from '../../projectStore.js';

// Verbs that bring a resource into existence (vs describe/list/tag/delete).
const CREATE_RE = /\b(create-|run-instances|run-task|provision-|register-|allocate-address)/i;

// "service operation" signature, e.g. "rds create-db-instance" — used to tell a
// genuinely-failed creation from one the agent retried and eventually succeeded.
function opSignature(action) {
    const m = String(action).match(/\baws\s+([a-z0-9-]+)\s+([a-z0-9-]+)/i);
    return m ? `${m[1]} ${m[2]}` : String(action).trim().slice(0, 60);
}

// Split the deploy log into successful and (genuinely) failed creation commands.
function classifyCreations(log) {
    const succeededSigs = new Set();
    for (const op of log) if (!op.error && CREATE_RE.test(op.action)) succeededSigs.add(opSignature(op.action));

    const succeeded = [];
    const failed = [];
    const seenFail = new Set();
    for (const op of log) {
        if (!CREATE_RE.test(op.action)) continue;
        if (!op.error) {
            succeeded.push(op.action.replace(/\s+/g, ' ').slice(0, 120));
            continue;
        }
        const sig = opSignature(op.action);
        if (succeededSigs.has(sig) || seenFail.has(sig)) continue; // retried OK, or already noted
        seenFail.add(sig);
        failed.push({ signature: sig, error: String(op.error).split('\n')[0].slice(0, 220) });
    }
    return { succeeded, failed };
}

// Ask the cheap model which node IDs were NOT deployed, given the full log.
async function identifyFailedNodes(d2, succeeded, failed, emit) {
    const prompt = fill(await loadPrompt(import.meta.url), {
        D2_CURRENT_STATE: d2,
        SUCCEEDED_OPERATIONS: succeeded.length ? succeeded.map((s) => `- ${s}`).join('\n') : '(none)',
        FAILED_OPERATIONS: failed.map((f) => `- ${f.signature}: ${f.error}`).join('\n')
    });
    await store.archivePrompt(prompt);

    let text = '';
    try {
        const stream = getGemini().messages.stream({
            model: MODELS.reconciler,
            max_tokens: 1000,
            messages: [{ role: 'user', content: prompt }]
        });
        const message = await stream.finalMessage();
        text = message.content.filter((b) => b.type === 'text').map((b) => b.text).join('');
    } catch {
        emit({ type: 'status', text: 'Could not map deploy failures to diagram nodes.' });
        return [];
    }

    const t = stripCodeFences(text).trim();
    let ids = [];
    try {
        const arr = JSON.parse(t);
        if (Array.isArray(arr)) ids = arr;
    } catch {
        const m = t.match(/"([\w-]+)"/g);
        if (m) ids = m.map((s) => s.replace(/"/g, ''));
    }
    return ids.map((x) => String(x).split('.').pop()).filter(Boolean);
}

// Returns { deployState, diagramChanged }.
//   deployState: 'none'     — nothing was created (empty log / all errors); caller stays in preview.
//                'deployed' — every resource came up; diagram is the clean design.
//                'partial'  — some resources failed; diagram has them marked in red.
//   diagramChanged: whether the stored diagram was rewritten (caller repaints).
export async function runReconciler(emit) {
    const [currentD2, workflow] = await Promise.all([store.readDiagram(), store.readWorkflow()]);
    await store.clearQueue();

    // The clean design is the stored diagram minus any prior failure marks.
    const cleanD2 = stripAnnotations(currentD2);

    // Nothing created (no log, or every call errored) → failed deploy, stay preview.
    if (workflow.length === 0 || !workflow.some((op) => !op.error)) {
        return { deployState: 'none', diagramChanged: false };
    }

    const { succeeded, failed } = classifyCreations(workflow);

    // Everything deployed → show the clean design (drop any marks from a prior partial).
    if (failed.length === 0) {
        const changed = cleanD2.trim() !== currentD2.trim();
        if (changed) await store.writeDiagram(cleanD2);
        emit({ type: 'status', text: 'All resources deployed — showing the full architecture.' });
        return { deployState: 'deployed', diagramChanged: changed };
    }

    emit({ type: 'status', text: 'Marking resources that could not be deployed…' });
    const leaves = await identifyFailedNodes(cleanD2, succeeded, failed, emit);
    const model = buildNodeModel(cleanD2);
    const annotated = annotateFailedNodes(cleanD2, leaves, model);

    if (!annotated) {
        // Failures didn't map to any drawn node → treat as fully deployed.
        const changed = cleanD2.trim() !== currentD2.trim();
        if (changed) await store.writeDiagram(cleanD2);
        return { deployState: 'deployed', diagramChanged: changed };
    }

    await store.writeDiagram(annotated);
    emit({ type: 'status', text: 'Some resources could not be deployed — marked in red. Retry deploy or tear down.' });
    return { deployState: 'partial', diagramChanged: true };
}
